#
# (C) Copyright 2017
# Thomas Schaefer, Kontron Europe GmbH, thomas.schaefer@kontron.com
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_KEX_IMX_WATCHDOG) += imx_watchdog.o

# if kjtag support is required, include jamStapl
obj-$(CONFIG_JAM_STAPL) += jamStapl/
